### ISSUE TITLE
Thanks for your sharing! But the link of the pretrained model is invalid now. Could you please upload the pretrained model~

### ISSUE THREAD

**Issue by pjl1995** [zhangqianhui/GazeAnimation#1]

**Comment by zhangqianhui** [comment]
Now I will upload the pretrained model of GazeGAN. When GazeAnimation finishs the training, I will upload it.

**Comment by pjl1995** [comment]
Thanks! Another problem: In 0.txt and 1.txt of CelebAGaze dataset, there are 4 numbers for every image. What do the 4 numbers represents? Maybe I think is the Eyeball position. If I use my own data, do I need to get these 4 numbers first?

**Comment by pjl1995** [comment]
Thanks! I think your work is really meaningful！
I want to ask another problem. In 0.txt and 1.txt of CelebAGaze dataset, there are 4 numbers for every image. What do the 4 numbers represents? Maybe I think is the eyeball position. And the size of every image is 256*256.
If I use my own data, such as a 1280*720 size image (including the person and the background), how can I use the GazeGan or GazeAnimation? Do I need to crop the face area image and resize it to 256*256? And maybe I need use another face key point algorithm to get the eyeball position?
Looking forward to your answer. Thank you!

**Comment by pjl1995** [comment]
Thanks! I think your work is really meaningful！
I want to ask another problem. In 0.txt and 1.txt of CelebAGaze dataset, there are 4 numbers for every image. What do the 4 numbers represents? Maybe I think is the eyeball position. And the size of every image is 256*256.
If I use my own data, such as a 1280*720 size image (including the person and the background), how can I use the GazeGan or GazeAnimation? Do I need to crop the face area image and resize it to 256*256? And maybe I need use another face key point algorithm to get the eyeball position?
Looking forward to your answer. Thank you!

**Comment by pjl1995** [comment]
Thanks! I think your work is really meaningful！
I want to ask another problem. In 0.txt and 1.txt of CelebAGaze dataset, there are 4 numbers for every image. What do the 4 numbers represents? Maybe I think is the eyeball position. And the size of every image is 256x256.
If I use my own data, such as a 1280x720 size image (including the person and the background), how can I use the GazeGan or GazeAnimation? Do I need to crop the face area image and resize it to 256x256? And maybe I need use another face key point algorithm to get the eyeball position?
Looking forward to your answer. Thank you!

**Comment by zhangqianhui** [comment]
Q1: what do the four numbers representing?
A1: x1, y1; x2, y2. They represents the center point of eyes region. You can read the code of geteye_pos in GazeGAN.py

Q2: If I use my own data, such as a 1280x720 size image (including the person and the background), how can I use the GazeGan or GazeAnimation?  Do I need to crop the face area image and resize it to 256x256? 

You can use dlib to extract the features points of eye region and compute the center points. The details can be found in Dataset section in this paper. Additionally, it will be better to use face alignment algorithm to align your data.
