### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by shalinidemello** [zhangqianhui/GazeAnimation#4]
How can I install the following dependencies using pip (python 3.6):

block-extractor-cuda==0.0.0
local-attn-reshape-cuda==0.0.0
mkl-service==2.3.0
resample2d-cuda==0.0.0

These are not available via pip.

**Comment by zhangqianhui** [comment]
sorry
You can use conda 

-conda create -name GazeA python=3.6
-conda install tensorflow-gpu=1.9 or higher

Then, you can use pip to install some missing packages.

**Comment by shalinidemello** [comment]
So, will conda install the cuda-related packages?

**Comment by zhangqianhui** [comment]
Yes， you can try. Have you solved this problem?
