### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by ALONGNEU** [zhangqianhui/GazeAnimation#9]
Thank you for sharing this great work!

The training time you mentioned in the paper is 10 hours, but when I try the training progress(Tesla M40, compute capability is 5.2), it needs more than 4 days with the default configuration of the code.
Is somewhere I need to modify?
Thanks again.

**Comment by zhangqianhui** [comment]
hi, this code will converge with 10 hours on the Titanx GPU. It maybe attains better results with more iterations.

**Comment by ALONGNEU** [comment]
> hi, this code will converge with 10 hours on the Titanx GPU. It maybe attains better results with more iterations.

So, how many steps does it take to converge?

**Comment by zhangqianhui** [comment]
Hi, you can verify it by the generated samples.
